
import Groq from 'groq-sdk'
import { Resume } from '../resume/resume.model'
import { buildTailoringPrompt } from './cv-tailoring.prompt'

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

export async function tailorResume(resumeId: string, jobDescription: string) {
  const resume = await Resume.findById(resumeId)
  if (!resume) throw new Error('Resume not found')

  const prompt = buildTailoringPrompt(resume.rawText, jobDescription)

  const response = await groq.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [{ role: 'user', content: prompt }],
    temperature: 0.4,
    max_tokens: 1024,
  })

  const content = response.choices[0]?.message?.content
  if (!content) throw new Error('No response from Groq')

  const cleaned = content.replace(/```json|```/g, '').trim()
  const tailored = JSON.parse(cleaned)

  return { resumeId, jobDescription, tailored }
}

// ─── Auto-Apply Stub ──────────────────────────────────────────────
// Future: Chrome extension will call this endpoint to auto-fill job forms
// For now simulate the intent

export async function autoApplyStub(resumeId: string, jobUrl: string) {
  // TODO: Chrome extension integration
  // 1. Extension detects job application form
  // 2. Calls this endpoint with jobUrl
  // 3. Backend returns tailored field values
  // 4. Extension auto-fills the form

  return {
    resumeId,
    jobUrl,
    status: 'stub',
    message: 'Auto-apply workflow initiated. Chrome extension integration pending.',
    simulatedFields: {
      name: 'Extracted from resume',
      email: 'Extracted from resume',
      coverLetter: 'Generated by CV tailoring module',
    },
  }
}